var annotated_dup =
[
    [ "Minisat", null, [
      [ "BoolOption", "class_minisat_1_1_bool_option.html", null ],
      [ "Clause", "class_minisat_1_1_clause.html", null ],
      [ "ClauseAllocator", "class_minisat_1_1_clause_allocator.html", null ],
      [ "ClauseIterator", "class_minisat_1_1_clause_iterator.html", null ],
      [ "CMap", "class_minisat_1_1_c_map.html", null ],
      [ "DeepEqual", "struct_minisat_1_1_deep_equal.html", null ],
      [ "DeepHash", "struct_minisat_1_1_deep_hash.html", null ],
      [ "DoubleOption", "class_minisat_1_1_double_option.html", null ],
      [ "DoubleRange", "struct_minisat_1_1_double_range.html", null ],
      [ "Equal", "struct_minisat_1_1_equal.html", null ],
      [ "Hash", "struct_minisat_1_1_hash.html", null ],
      [ "Heap", "class_minisat_1_1_heap.html", null ],
      [ "Int64Option", "class_minisat_1_1_int64_option.html", null ],
      [ "Int64Range", "struct_minisat_1_1_int64_range.html", null ],
      [ "IntMap", "class_minisat_1_1_int_map.html", null ],
      [ "IntOption", "class_minisat_1_1_int_option.html", null ],
      [ "IntRange", "struct_minisat_1_1_int_range.html", null ],
      [ "IntSet", "class_minisat_1_1_int_set.html", null ],
      [ "lbool", "class_minisat_1_1lbool.html", null ],
      [ "LessThan_default", "struct_minisat_1_1_less_than__default.html", null ],
      [ "Lit", "struct_minisat_1_1_lit.html", null ],
      [ "LMap", "class_minisat_1_1_l_map.html", null ],
      [ "LSet", "class_minisat_1_1_l_set.html", null ],
      [ "Map", "class_minisat_1_1_map.html", "class_minisat_1_1_map" ],
      [ "MkIndexDefault", "struct_minisat_1_1_mk_index_default.html", null ],
      [ "MkIndexLit", "struct_minisat_1_1_mk_index_lit.html", null ],
      [ "OccLists", "class_minisat_1_1_occ_lists.html", null ],
      [ "Option", "class_minisat_1_1_option.html", "class_minisat_1_1_option" ],
      [ "OutOfMemoryException", "class_minisat_1_1_out_of_memory_exception.html", null ],
      [ "Queue", "class_minisat_1_1_queue.html", null ],
      [ "RegionAllocator", "class_minisat_1_1_region_allocator.html", null ],
      [ "SimpSolver", "class_minisat_1_1_simp_solver.html", "class_minisat_1_1_simp_solver" ],
      [ "Solver", "class_minisat_1_1_solver.html", "class_minisat_1_1_solver" ],
      [ "StreamBuffer", "class_minisat_1_1_stream_buffer.html", null ],
      [ "StringOption", "class_minisat_1_1_string_option.html", null ],
      [ "TrailIterator", "class_minisat_1_1_trail_iterator.html", null ],
      [ "vec", "class_minisat_1_1vec.html", null ],
      [ "VMap", "class_minisat_1_1_v_map.html", null ]
    ] ],
    [ "reduceDB_lt", "structreduce_d_b__lt.html", null ]
];